export const categoryContent: Record<string, { title: string; description: string }> = {
  // Tech subcategories
  'tech/ai': {
    title: 'AI in Tech',
    description: 'Artificial Intelligence (AI) is revolutionizing the way we live and work, ushering in a new era of innovation that is reshaping industries and transforming everyday experiences. By leveraging advanced algorithms, machine learning, and data analysis, AI systems are enabling machines to perform tasks that traditionally required human intelligence—such as recognizing patterns, making decisions, and learning from experience. This powerful technology is not only increasing efficiency and productivity but also opening up new possibilities that were once unimaginable. One of the most profound ways AI is changing our lives is through predictive algorithms. These systems analyze vast amounts of data to forecast trends, behaviors, and outcomes with remarkable accuracy. In healthcare, for example, AI-powered predictive models help diagnose diseases earlier and tailor treatments to individual patients, improving outcomes and saving lives. In finance, predictive analytics assist in fraud detection and risk assessment, making transactions safer and more reliable. Even in everyday technology, AI predictions shape the content we see on social media and streaming platforms, personalizing experiences to match our preferences and habits. Autonomous systems represent another groundbreaking application of AI, especially in industries like transportation and manufacturing. Self-driving cars are becoming increasingly sophisticated, promising safer roads by reducing human error and enabling more efficient traffic flow. In warehouses and factories, AI-driven robots handle repetitive and physically demanding tasks, freeing human workers to focus on more complex and creative responsibilities. These autonomous systems not only enhance productivity but also improve safety and reduce costs. AI is also fostering innovation by enabling smarter decision-making processes across sectors. In agriculture, AI-powered sensors and drones monitor crop health and optimize resource use, promoting sustainable farming practices. In customer service, chatbots and virtual assistants provide instant support, improving responsiveness and user satisfaction. The integration of AI with the Internet of Things (IoT) is creating intelligent environments—from smart homes that adjust lighting and temperature automatically to cities that optimize energy consumption and traffic management. '
  },
  'tech/web-development': {
    title: 'Web Development',
    description: 'Web development is the dynamic and essential discipline that brings modern websites and web applications to life. It encompasses two fundamental areas: frontend development, which focuses on the parts of a website users interact with directly, and backend development, which manages the behind-the-scenes processes that make a website function. Together, these two sides of web development create seamless, interactive, and efficient online experiences that define the digital age. Frontend development—often referred to as the "client side"—is all about designing and building the interface of a website. It involves the use of languages like HTML, CSS, and JavaScript to structure content, apply styles, and add interactivity. Frontend developers are responsible for making sure a site looks visually appealing and works smoothly across different devices and browsers. They implement responsive design so that a website adapts to various screen sizes, ensuring a consistent user experience. With modern frameworks like React, Vue, and Angular, developers can create dynamic, single-page applications that respond instantly to user input, mimicking the behavior of desktop software within a browser. Frontend development—often referred to as the "client side"—is all about designing and building the interface of a website. It involves the use of languages like HTML, CSS, and JavaScript to structure content, apply styles, and add interactivity. Frontend developers are responsible for making sure a site looks visually appealing and works smoothly across different devices and browsers. They implement responsive design so that a website adapts to various screen sizes, ensuring a consistent user experience. With modern frameworks like React, Vue, and Angular, developers can create dynamic, single-page applications that respond instantly to user input, mimicking the behavior of desktop software within a browser. The synergy between frontend and backend development is what enables modern websites to be not just static pages, but powerful platforms for communication, commerce, education, and entertainment. For instance, when a user submits a form on a website, the frontend captures the data and sends it to the backend, which processes it, stores it in a database, and responds appropriately—perhaps by sending a confirmation message or updating the users profile. This real-time exchange of data and functionality is at the heart of modern web experiences'
  },
  

  // Sustainability subcategories
  'sustainability/green-energy': {
    title: 'Green Energy',
    description: 'Green energy, also known as renewable energy, is derived from natural sources that are replenished constantly—sunlight, wind, and water being the most prominent. Unlike fossil fuels, these energy sources do not emit carbon dioxide or other greenhouse gases when generating electricity. Their sustainable nature makes them a cornerstone of climate action strategies worldwide. Solar energy is one of the most accessible and abundant forms of renewable energy. By converting sunlight into electricity using photovoltaic (PV) panels or solar thermal systems, solar power provides a clean alternative to coal, oil, and natural gas. Every kilowatt-hour (kWh) of solar power used in place of fossil fuels prevents the release of nearly one kilogram of CO₂. Moreover, solar energy can be deployed at various scales—from rooftop panels on homes to large solar farms powering entire communities—making it a versatile solution for reducing emissions globally. '
  },
  'sustainability/eco-products': {
    title: 'Eco-Friendly Products',
    description: 'Eco-products, often referred to as environmentally friendly or sustainable products, are designed and manufactured with a deep awareness of their impact on the planet. At the heart of their creation lies a commitment to minimizing environmental harm throughout a products entire life cycle—from sourcing raw materials, through production and usage, to final disposal or recycling. This approach stands in stark contrast to traditional production methods that often prioritize efficiency and cost at the expense of the environment. The journey of an eco-product begins with the choice of materials. Manufacturers favor renewable, biodegradable, or recycled inputs over finite or non-recyclable resources. For instance, bamboo, which grows rapidly without the need for fertilizers or pesticides, is often used in place of plastic or hardwood. Similarly, recycled metals, plastics, and fabrics reduce the demand for virgin resources and help divert waste from landfills. This careful material selection not only preserves ecosystems but also significantly lowers the carbon footprint associated with extraction and processing. In the production phase, sustainable practices are employed to further reduce environmental impact. This can include the use of energy-efficient machinery, reliance on renewable energy sources like solar or wind in factories, and the implementation of zero-waste manufacturing techniques. Water conservation and safe chemical use are also prioritized to prevent pollution and resource depletion. Moreover, ethical labor practices and transparent supply chains ensure that eco-products are socially responsible as well as environmentally sound.'
  },
  'sustainability/climate-change': {
    title: 'Climate Change',
    description: 'Climate change stands today as one of the most urgent and far-reaching challenges facing humanity. It is driven primarily by the accumulation of greenhouse gases (GHGs) in the Earths atmosphere—most notably carbon dioxide (CO₂), methane (CH₄), and nitrous oxide (N₂O). These gases are released through human activities such as burning fossil fuels, deforestation, industrial processes, and large-scale agriculture. As their concentration rises, they trap more heat within the atmosphere, disrupting the planets natural climate systems and causing a global increase in temperatures—a phenomenon commonly referred to as global warming. The roots of this problem trace back to the Industrial Revolution, when coal and later oil and gas became the primary energy sources for powering factories, transportation, and homes. Since then, the scale of emissions has grown exponentially. Today, the combustion of fossil fuels for electricity, heating, and transportation is the largest source of anthropogenic GHGs. In addition, land-use changes—especially the clearing of forests—have significantly reduced the Earth ability to absorb carbon dioxide, compounding the problem further. The consequences of climate change are already visible across the globe. Rising average temperatures have led to more frequent and severe heatwaves, shifting weather patterns, and intensified storms and floods. Polar ice is melting at alarming rates, causing sea levels to rise and threatening coastal communities. Agriculture is under pressure, with changing rainfall patterns and extreme weather events reducing crop yields and food security in many regions. These impacts not only affect the environment but also have profound social, economic, and political implications—especially for the world most vulnerable populations'
  },
  'sustainability/sustainable-living': {
    title: 'Sustainable Living',
    description: 'Sustainable living is a lifestyle choice centered on making conscious decisions that promote the health and well-being of our planet. It involves adopting habits and practices that reduce our environmental footprint while fostering a balance between human needs and the Earth&rsquo;s natural resources. At its core, sustainable living is about recognizing the interconnectedness between our daily actions and the broader health of the environment, and actively choosing to support a future where both people and the planet can thrive. One of the fundamental aspects of sustainable living is reducing waste. In a world where consumption often exceeds necessity, waste generation has become a pressing issue. Sustainable living encourages individuals to rethink their consumption habits by prioritizing quality over quantity, repairing instead of replacing, and choosing reusable products instead of disposable ones. This approach helps minimize landfill overflow and reduces pollution, as less waste means fewer resources are extracted, processed, and ultimately discarded. Composting organic waste and recycling materials like paper, glass, and plastics also play a crucial role in cutting down the environmental burden associated with waste disposal. Conserving energy is another vital component of sustainable living. Our reliance on fossil fuels for electricity and transportation has been a major contributor to climate change and environmental degradation. By adopting energy-efficient practices—such as using LED lighting, turning off appliances when not in use, insulating homes, and choosing renewable energy sources—individuals can significantly lower their carbon footprint. Additionally, opting for sustainable transportation methods like walking, cycling, carpooling, or using public transit not only conserves energy but also reduces air pollution and traffic congestion.'
  },
};

